name: Build Android APK
on: [push, pull_request]

jobs:
  build-android:
    name: Build para Android
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Instalar dependencias del sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf automake cmake gettext libtool pkg-config \
          libffi-dev libssl-dev python3-pip openjdk-11-jdk \
          ninja-build build-essential

    - name: Instalar Cython y herramientas Python
      run: |
        pip3 install --user --upgrade Cython==0.29.36 virtualenv
        pip3 install --user buildozer

    - name: Configurar cache de Buildozer
      uses: actions/cache@v4
      with:
        path: |
          .buildozer_global
          .buildozer
        key: buildozer-cache-${{ hashFiles('buildozer.spec') }}

    - name: Compilar con Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        command: |
          buildozer android clean
          buildozer android debug
        buildozer_version: stable
        workdir: .

    - name: Subir APK como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: "**/*.apk"
        retention-days: 7
