name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Instalar dependencias del sistema
      run: |
        sudo apt-get update
        # Solucionar problema de libtinfo5 en Ubuntu 24.04
        sudo apt-get install -y libtinfo6
        sudo ln -s /usr/lib/x86_64-linux-gnu/libtinfo.so.6 /usr/lib/x86_64-linux-gnu/libtinfo.so.5
        
        # Instalar todas las dependencias necesarias :cite[2]
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          python3-pip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          cmake \
          libffi-dev \
          libssl-dev \
          automake \
          wget

    - name: Instalar Buildozer y Cython
      run: |
        pip3 install --user --upgrade Cython==0.29.33 virtualenv
        pip3 install --user buildozer

    - name: Configurar Android SDK y aceptar licencias
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        # Crear directorio para licencias
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        
        # Configurar variables de entorno para Android SDK
        export ANDROID_HOME="$HOME/.buildozer/android/platform/android-sdk"
        export ANDROID_SDK_ROOT="$ANDROID_HOME"
        
        # Aceptar todas las licencias automáticamente :cite[2]
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        
        # Instalar versiones específicas de build-tools y plataformas :cite[2]
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" "platforms;android-31" "platform-tools"

    - name: Compilar APK con Buildozer
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        # Forzar la actualización y compilar
        buildozer android clean
        buildozer -v android debug

    - name: Subir APK como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: AzojuanitoP41-APK
        path: bin/*.apk
        retention-days: 30
