name: Build Android APK for AzojuanitoP41

on: [push, pull_request]

jobs:
  build-android:
    name: Build APK for AzojuanitoP41
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        command: |
          buildozer android clean
          buildozer android debug
        buildozer_version: stable
        workdir: .
      options: --user root  # This line fixes the 'chown' error

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: AzojuanitoP41-apk
        path: "bin/*.apk"
        retention-days: 7
